version: '3'
services:

  redis:
    image: redis
  
  postgres:
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=AuthService
      - REDIS_HOST=redis

  backend:
    build:
      context: .
      dockerfile: Dockerfile

    ports:
      - 8000:8000
    environment:
      - NODE_ENV=docker



